// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VMwareMachineClassLister helps list VMwareMachineClasses.
type VMwareMachineClassLister interface {
	// List lists all VMwareMachineClasses in the indexer.
	List(selector labels.Selector) (ret []*machine.VMwareMachineClass, err error)
	// VMwareMachineClasses returns an object that can list and get VMwareMachineClasses.
	VMwareMachineClasses(namespace string) VMwareMachineClassNamespaceLister
	VMwareMachineClassListerExpansion
}

// vMwareMachineClassLister implements the VMwareMachineClassLister interface.
type vMwareMachineClassLister struct {
	indexer cache.Indexer
}

// NewVMwareMachineClassLister returns a new VMwareMachineClassLister.
func NewVMwareMachineClassLister(indexer cache.Indexer) VMwareMachineClassLister {
	return &vMwareMachineClassLister{indexer: indexer}
}

// List lists all VMwareMachineClasses in the indexer.
func (s *vMwareMachineClassLister) List(selector labels.Selector) (ret []*machine.VMwareMachineClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.VMwareMachineClass))
	})
	return ret, err
}

// VMwareMachineClasses returns an object that can list and get VMwareMachineClasses.
func (s *vMwareMachineClassLister) VMwareMachineClasses(namespace string) VMwareMachineClassNamespaceLister {
	return vMwareMachineClassNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VMwareMachineClassNamespaceLister helps list and get VMwareMachineClasses.
type VMwareMachineClassNamespaceLister interface {
	// List lists all VMwareMachineClasses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*machine.VMwareMachineClass, err error)
	// Get retrieves the VMwareMachineClass from the indexer for a given namespace and name.
	Get(name string) (*machine.VMwareMachineClass, error)
	VMwareMachineClassNamespaceListerExpansion
}

// vMwareMachineClassNamespaceLister implements the VMwareMachineClassNamespaceLister
// interface.
type vMwareMachineClassNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VMwareMachineClasses in the indexer for a given namespace.
func (s vMwareMachineClassNamespaceLister) List(selector labels.Selector) (ret []*machine.VMwareMachineClass, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.VMwareMachineClass))
	})
	return ret, err
}

// Get retrieves the VMwareMachineClass from the indexer for a given namespace and name.
func (s vMwareMachineClassNamespaceLister) Get(name string) (*machine.VMwareMachineClass, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(machine.Resource("vmwaremachineclass"), name)
	}
	return obj.(*machine.VMwareMachineClass), nil
}
