// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VsphereMachineClassLister helps list VsphereMachineClasses.
type VsphereMachineClassLister interface {
	// List lists all VsphereMachineClasses in the indexer.
	List(selector labels.Selector) (ret []*machine.VsphereMachineClass, err error)
	// VsphereMachineClasses returns an object that can list and get VsphereMachineClasses.
	VsphereMachineClasses(namespace string) VsphereMachineClassNamespaceLister
	VsphereMachineClassListerExpansion
}

// vsphereMachineClassLister implements the VsphereMachineClassLister interface.
type vsphereMachineClassLister struct {
	indexer cache.Indexer
}

// NewVsphereMachineClassLister returns a new VsphereMachineClassLister.
func NewVsphereMachineClassLister(indexer cache.Indexer) VsphereMachineClassLister {
	return &vsphereMachineClassLister{indexer: indexer}
}

// List lists all VsphereMachineClasses in the indexer.
func (s *vsphereMachineClassLister) List(selector labels.Selector) (ret []*machine.VsphereMachineClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.VsphereMachineClass))
	})
	return ret, err
}

// VsphereMachineClasses returns an object that can list and get VsphereMachineClasses.
func (s *vsphereMachineClassLister) VsphereMachineClasses(namespace string) VsphereMachineClassNamespaceLister {
	return vsphereMachineClassNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VsphereMachineClassNamespaceLister helps list and get VsphereMachineClasses.
type VsphereMachineClassNamespaceLister interface {
	// List lists all VsphereMachineClasses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*machine.VsphereMachineClass, err error)
	// Get retrieves the VsphereMachineClass from the indexer for a given namespace and name.
	Get(name string) (*machine.VsphereMachineClass, error)
	VsphereMachineClassNamespaceListerExpansion
}

// vsphereMachineClassNamespaceLister implements the VsphereMachineClassNamespaceLister
// interface.
type vsphereMachineClassNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VsphereMachineClasses in the indexer for a given namespace.
func (s vsphereMachineClassNamespaceLister) List(selector labels.Selector) (ret []*machine.VsphereMachineClass, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.VsphereMachineClass))
	})
	return ret, err
}

// Get retrieves the VsphereMachineClass from the indexer for a given namespace and name.
func (s vsphereMachineClassNamespaceLister) Get(name string) (*machine.VsphereMachineClass, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(machine.Resource("vspheremachineclass"), name)
	}
	return obj.(*machine.VsphereMachineClass), nil
}
